from typing import Optional
import pandas as pd


class Orchestrator:
    """
    Central controller that coordinates communication and shared state
    between different agents (here SQLAgent and VisualizationAgent).

    Attributes
    ----------
    current_dataframe : Optional[pd.DataFrame]
        Stores the most recent DataFrame loaded or generated by any agent.
    sql_agent : Optional[SQLAgent]
        Reference to the SQLAgent instance.
    viz_agent : Optional[VisualizationAgent]
        Reference to the VisualizationAgent instance.
    """

    def __init__(self):
        self.current_dataframe: Optional[pd.DataFrame] = None
        self.sql_agent = None
        self.viz_agent = None

    def set_dataframe(self, df: pd.DataFrame):
        """Store a DataFrame for use by all agents."""
        self.current_dataframe = df

    def get_dataframe(self) -> Optional[pd.DataFrame]:
        """Retrieve the currently shared DataFrame."""
        return self.current_dataframe

    def register_sql_agent(self, agent):
        """Attach a SQLAgent instance."""
        self.sql_agent = agent

    def register_visualization_agent(self, agent):
        """Attach a VisualizationAgent instance."""
        self.viz_agent = agent

    def clear_dataframe(self):
        """Reset the shared DataFrame."""
        self.current_dataframe = None
